### ISSUE TITLE
Change Detection not working after the upgrade to universal-preview 0.82.0 and Angular 2 beta-12

### ISSUE THREAD

**Issue by jhades** [angular/universal-starter#56]
I just tried the following:

- using node 4.2.1 and npm 3.7.5
- clean clone of the project
- npm install
- npm run build
- npm start
- go to http://localhost:3000/

The page gets rendered on the server side correctly, but change detection is not working.

What i mean by that is that as we type on the input text field, the title of the page does not get updated.
By trying with a keydown event, we get the same result:
 
    <input type="text" [value]="name" (keydown)="name = input.value" autofocus #input>{{name}}

There are no errors in the console.

**Comment by joaogarin** [comment]
Same thing here : https://github.com/angular/universal-starter/issues/55

Also when setting async to true and preboot to true.

**Comment by jhades** [comment]
@joaogarin I noticed they are both set to false on the starter.How do these flags work? Thxs

**Comment by joaogarin** [comment]
Yes I think they should be set to true for preboot to take effect and start recording events before client side app is fully loaded. I am not sure if this is required for the change detection to work, don't think so.

You can read more about it here : https://github.com/angular/universal/tree/master/modules/preboot

**Comment by bjwyse** [comment]
Two issues are preventing this from working as is.

The client side JS is not being included in the rendered HTML page because the script tags are not allowed in templates I believe.

Moving the script back to index.html will resolve this issue. See https://github.com/bjwyse/universal-starter/commit/95401e8c6f0e233010078226cf82ea63e063437a

Also, the latest Angular2 beta version (11) has a bug which prevents the client side from working even when the script is included. See https://github.com/angular/angular/pull/7702

I fixed this by applying the fix to node_modules/angular2/src/core/zone/ng_zone_impl.js directly in line 26. It should be fixed in the next beta release I assume.

**Comment by jhades** [comment]
About this part:

> The client side JS is not being included in the rendered HTML page because the script tags are not allowed in templates I believe

According to these docs https://angular.io/docs/ts/latest/guide/template-syntax.html:

> Almost all HTML syntax is valid template syntax. The <script> element is a notable exception; it is forbidden, eliminating the risk of script injection attacks. (In practice, <script> is simply ignored.)

**Comment by jhades** [comment]
I've tried this just now with beta-12, and the issue remains. The application boots up and there is no error in either the server or the client. 

But when typing on the input field, the hello message on the screen does not get updated.

**Comment by gdi2290** [comment]
thanks for the issue, everything works in latest changes so feel free to try it out again. Please reopen if you still have this issue

**Comment by jhades** [comment]
It works, thanks!
